project_id = "hltrcuypuxhetcjyvedl"

[functions.create-setup-intent]
verify_jwt = false

[functions.get-payment-methods]
verify_jwt = false

[functions.create-checkout-setup]
verify_jwt = false

[functions.delete-payment-method]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.bay-controller-api]
verify_jwt = false

[functions.create-membership-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
